routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TileController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('/weather', [HomeController::class, 'weatherAPI'])->name('weather_api');


Route::group(['prefix' => 'tiles', 'as' => 'tile.'], function () {
    Route::get('tiles/{id}', [TileController::class, 'delete'])->name('delete');
});

app/Models/Forecast.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Forecast extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function getTimeFormatAttribute(){
        $time = Carbon::parse($this->time)->format('Y-m-d H:i');
        
        return $time;
    }
}

resources/views/component/forecast_modal.blade.php
<div class="modal fade" id="modal-{{$tile->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-xl">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Weather Forecast</h5>

                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @foreach($tile->forecasts as $forecast)
                <div class="col tile">
                    <div class="card">
                        <div class="row">
                            <div class="col-xl-5">
                                <div class="text-center p-4 border-end">
                                    <div class=" avatar-sm mx-auto mb-3 mt-1">
                                        <span class="avatar-title rounded-circle bg-danger bg-soft text-danger font-size-16">
                                            <img src="{{ asset("assets/images/icon/$forecast->icon@2x.png") }}">
                                        </span>
                                    </div>
                                </div>
                                <div>
                                    <h5 class="text-center">{{$forecast->situation}}</h5>
                                    <p class="text-center">{{$forecast->description}}</p>
                                </div>
                            </div>

                            <div class="col-xl-7">
                                <div class="p-4 text-center text-xl-start">
                                    <div class="row">
                                        <div class="col-12">
                                            <div>
                                                <p class="text-muted mb-2 text-truncate">Date : </p>
                                                <h5>{{$forecast->time_format}}</h5>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div>
                                                <p class="text-muted mb-2 text-truncate">Temperature : </p>
                                                <h5>{{$forecast->temperature}} °C</h5>
                                            </div>
                                        </div>
                                    </div>
                                   
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div>

resources/views/component/tile.blade.php
<div class="col tile" id="tile-{{$tile->id}}">
    <div class="card">
        <div class="row">
            <div class="col-xl-5">
                <div class="text-center p-4 border-end">
                    <div class=" avatar-sm mx-auto mb-3 mt-1">
                        <span class="avatar-title rounded-circle bg-danger bg-soft text-danger font-size-16">
                            <img src="{{ asset("assets/images/icon/$tile->icon@2x.png") }}">
                        </span>
                    </div>
                </div>
                <div>
                    <h5 class="text-center">{{$tile->situation}}</h5>
                    <p class="text-center">{{$tile->description}}</p>
                </div>
            </div>

            <div class="col-xl-7">
                <div class="p-4 text-center text-xl-start">
                    <div class="row">
                        <div class="col-12">
                            <div>
                                <p class="text-muted mb-2 text-truncate">Name : </p>
                                <h5>{{$tile->city}}, <small>{{$tile->state}} , {{$tile->country_code}}</small></h5>
                            </div>
                        </div>
                        <div class="col-12">
                            <div>
                                <p class="text-muted mb-2 text-truncate">Temperature : </p>
                                <h5>{{$tile->temperature}} °C</h5>
                            </div>
                        </div>
                    </div>
                    <div class="mt-4">

                        <a type="button" data-bs-toggle="modal" data-bs-target="#modal-{{$tile->id}}" class="text-decoration-underline text-reset mb-10">See Forecast<i class="mdi mdi-arrow-right"></i></a>
                        <br>
                        <br>
                        <a type="button" href="{{route('tile.delete', $tile->id)}}" class="btn btn-danger btn-rounded waves-effect waves-light">Delete</a>
                        <br>
                        <br>
                        <small class="text-right">Update interval : {{$tile->refresh_interval}} minute</small>
                        <br>
                        <small class="text-right">last update {{$tile->updated_at}}</small>
                        
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

resources/views/component/tile_layout.blade.php
<div class="flex-box">
    @forelse($tiles as $tile)

    @component('component.tile', ['tile'=> $tile])
    @endcomponent

    @component('component.forecast_modal', ['tile'=> $tile])
    @endcomponent

    @empty
    <p>There are no weather tile yet.</p>
    @endforelse

</div>